#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Comparison & Logical Operators Exercise

#### Find all the books written before 1980

In [2]:
%%sql

USE book_shop;

SELECT *
FROM books
WHERE released_year < 1980

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,14,Cannery Row,John,Steinbeck,1945,95,181

#### Find all the books written by Eggers or Chabon

In [3]:
%%sql

SELECT *
FROM books
WHERE author_lname IN ('Eggers', 'Chabon')

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352
1,6,The Circle,Dave,Eggers,2013,26,504
2,7,The Amazing Adventures of Kavalier & Clay,Michael,Chabon,2000,68,634
3,9,A Heartbreaking Work of Staggering Genius,Dave,Eggers,2001,104,437

#### Select all the books written by Lahiri and published after 2000

In [5]:
%%sql

SELECT *
FROM books
WHERE 
    author_lname = 'Lahiri' AND
    released_year > 2000

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,1,The Namesake,Jhumpa,Lahiri,2003,32,291

#### Find all the books with page counts between 100 and 200

In [7]:
%%sql

SELECT *
FROM books
WHERE pages BETWEEN 100 AND 200

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,4,Interpreter of Maladies,Jhumpa,Lahiri,1996,97,198
1,11,What We Talk About When We Talk About Love: St...,Raymond,Carver,1981,23,176
2,14,Cannery Row,John,Steinbeck,1945,95,181

#### Select all books where author_lname starts with a C or S

In [8]:
%%sql

SELECT *
FROM books
WHERE 
    author_lname LIKE 'C%' OR
    author_lname LIKE 'S%'

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,7,The Amazing Adventures of Kavalier & Clay,Michael,Chabon,2000,68,634
1,8,Just Kids,Patti,Smith,2010,55,304
2,11,What We Talk About When We Talk About Love: St...,Raymond,Carver,1981,23,176
3,12,Where I'm Calling From: Selected Stories,Raymond,Carver,1989,12,526
4,14,Cannery Row,John,Steinbeck,1945,95,181
5,19,Lincoln In The Bardo,George,Saunders,2017,1000,367

In [11]:
%%sql

SELECT
    title,
    author_lname, 
    CASE
        WHEN title LIKE '%stories%' THEN 'Short Stories'
        WHEN title LIKE '%Just Kids%' THEN 'Memoir'
        WHEN title LIKE '%Heartbreaking Work%' THEN 'Memoir'
        ELSE 'Novel'
    END AS TYPE
FROM books

,title,author_lname,TYPE
0,The Namesake,Lahiri,Novel
1,Norse Mythology,Gaiman,Novel
2,American Gods,Gaiman,Novel
3,Interpreter of Maladies,Lahiri,Novel
4,A Hologram for the King: A Novel,Eggers,Novel
5,The Circle,Eggers,Novel
6,The Amazing Adventures of Kavalier & Clay,Chabon,Novel
7,Just Kids,Smith,Memoir
8,A Heartbreaking Work of Staggering Genius,Eggers,Memoir
9,Coraline,Gaiman,Novel
10,What We Talk About When We Talk About Love: St...,Carver,Short Stories
11,Where I'm Calling From: Selected Stories,Carver,Short Stories
12,White Noise,DeLillo,Novel
13,Cannery Row,Steinbeck,Novel
14,Oblivion: Stories,Foster Wallace,Short Stories
15,Consider the Lobster,Foster Wallace,Novel
16,10% Happier,Harris,Novel
17,fake_book,Harris,Novel
18,Lincoln In The Bardo,Saunders,Novel

In [23]:
%%sql

SELECT 
    author_fname,
    author_lname,
    CONCAT(COUNT(*), (
            CASE
                WHEN COUNT(*) > 1 THEN ' books'
                ELSE 'book'
                END
    )) AS 'COUNT'
FROM books
GROUP BY author_fname, author_lname

   author_fname    author_lname    COUNT
0        Jhumpa          Lahiri  2 books
1          Neil          Gaiman  3 books
2          Dave          Eggers  3 books
3       Michael          Chabon    1book
4         Patti           Smith    1book
5       Raymond          Carver  2 books
6           Don         DeLillo    1book
7          John       Steinbeck    1book
8         David  Foster Wallace  2 books
9           Dan          Harris    1book
10       Freida          Harris    1book
11       George        Saunders    1book