#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Exercise - Create Table / Insert Data

## Define an Employees table, with the following fields:

- **id** — number (automatically increments) and primary key
- **last_name** — text, mandatory
- **first_name** — text, mandatory
- **middle_name** — text, not mandatory
- **age** — number, mandatory
- **current_status** — text, mandatory, defaults to `'employed'`

In [9]:
%%sql

USE dog_world;

CREATE TABLE employees
    (
        id INT AUTO_INCREMENT,
        last_name VARCHAR(50) NOT NULL,
        first_name VARCHAR(50) NOT NULL,
        middle_name VARCHAR(50),
        age INT NOT NULL,
        current_status VARCHAR(100) NOT NULL DEFAULT 'employed',
        PRIMARY KEY(id)
    )

Empty DataFrame
Columns: []
Index: []

In [10]:
%%sql

DESCRIBE employees

            Field          Type Null  Key   Default           Extra
0              id           int   NO  PRI      None  auto_increment
1       last_name   varchar(50)   NO           None
2      first_name   varchar(50)   NO           None
3     middle_name   varchar(50)  YES           None
4             age           int   NO           None
5  current_status  varchar(100)   NO       employed

In [11]:
%%sql

INSERT INTO employees (first_name, last_name, age, current_status)
VALUES
    ('Matt', 'Damon', 53, 'promoted'),
    ('Ben', 'Affleck', 70, 'terminated'),
    ('Roger', 'Federer', 50, DEFAULT),
    ('Christopher', 'Nolan', 80, 'promoted')

Empty DataFrame
Columns: []
Index: []

In [12]:
%%sql

SELECT *
FROM employees

   id last_name   first_name middle_name  age current_status
0   1     Damon         Matt        None   53       promoted
1   2   Affleck          Ben        None   70     terminated
2   3   Federer        Roger        None   50       employed
3   4     Nolan  Christopher        None   80       promoted

In [13]:
%%sql

DROP TABLE employees

Empty DataFrame
Columns: []
Index: []