#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Exercise

In [2]:
%%sql

USE dog_world;

SELECT cat_id
FROM cats

   cat_id
0       1
1       2
2       3
3       4
4       5
5       6
6       7

In [3]:
%%sql

SELECT
    name,
    breed
FROM cats

             name       breed
0           Ringo       Tabby
1           Cindy  Maine Coon
2      Dumbledore  Maine Coon
3             Egg     Persian
4           Misty       Tabby
5  George Michael     Ragdoll
6         Jackson      Sphynx

In [4]:
%%sql

SELECT 
    name,
    age
FROM cats 
WHERE breed = 'Tabby'

    name  age
0  Ringo    4
1  Misty   13

In [6]:
%%sql

SELECT
    cat_id,
    age
FROM cats 
WHERE cat_id = age

   cat_id  age
0       4    4
1       7    7