#### Connection with MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# DATE MATH

# DATEDIFF()
```sql
SELECT
    DATEDIFF('first_date', 'second_date')
FROM table_name
```

In [9]:
%%sql

USE dog_world;

SELECT 
    DATEDIFF(
        (
            SELECT (birth_date)
            FROM people
            WHERE name = 'Lulu'
        ),
        (
            SELECT (birth_Date)
            FROM people
            WHERE name = 'Matt'
        )
    )

   DATEDIFF(\n        (\n            SELECT (birth_date)\n            FROM people\n            WHERE name = 'Lulu'\n        ),\n        (\n            SELECT (birth_Date)\n            FROM people\n            WHERE name = 'Matt'\n        )\n    )
0                                                391

#### Calculating the age

In [16]:
%%sql

SELECT 
    name,
    birth_date,
    ROUND(DATEDIFF(CURDATE(), birth_date) / 365) AS Age
FROM people

    name  birth_date Age
0   Matt  2001-12-25  25
1   Lulu  2003-01-20  24
2    Ben  2010-10-02  16
3    Tom  2009-10-22  17
4  Peter  2001-11-28  25
5   Colt  2026-08-06   0

# DATE_ADD() / DATE_SUB()
```sql
SELECT
    DATE_ADD('your_date', INTERVAL 1 DAY )
FROM table_name
```
________
```sql
SELECT
    DATE_SUB('your_date', INTERVAL 1 YEAR )
FROM table_name
```

In [18]:
%%sql

SELECT 
    name, 
    birth_date,
    DATE_ADD(birth_date, INTERVAL 1 YEAR) AS add_1_year
FROM people

    name  birth_date  add_1_year
0   Matt  2001-12-25  2002-12-25
1   Lulu  2003-01-20  2004-01-20
2    Ben  2010-10-02  2011-10-02
3    Tom  2009-10-22  2010-10-22
4  Peter  2001-11-28  2002-11-28
5   Colt  2026-08-06  2027-08-06

#### Check when each of them turned or will turn 18 years of age

In [21]:
%%sql

SELECT 
    name,
    birth_date,
    DATE_ADD(birth_date, INTERVAL 18 YEAR) AS 'will reach 18'
FROM people

    name  birth_date will reach 18
0   Matt  2001-12-25    2019-12-25
1   Lulu  2003-01-20    2021-01-20
2    Ben  2010-10-02    2028-10-02
3    Tom  2009-10-22    2027-10-22
4  Peter  2001-11-28    2019-11-28
5   Colt  2026-08-06    2044-08-06

# TIMEDIFF

In [25]:
%%sql

SELECT 
    name,
    birth_time,
    TIMEDIFF(CURTIME(), birth_time)
FROM people

    name      birth_time TIMEDIFF(CURTIME(), birth_time)
0   Matt 0 days 11:00:00                 0 days 02:10:01
1   Lulu 0 days 23:59:10               -1 days +13:10:51
2    Ben 0 days 11:15:10                 0 days 01:54:51
3    Tom 0 days 13:01:30                 0 days 00:08:31
4  Peter 0 days 11:30:20                 0 days 01:39:41
5   Colt 0 days 09:51:57                 0 days 03:18:04