#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# DATE
#### Values with a DATE but no Time
#### YYYY-MM-DD format

# TIME
#### Values with a TIME but no Date
#### HH:MM:SS format

# DATETIME
#### Values with a Date and Time
#### YYYY-MM-DD HH:MM:SS Format

In [2]:
%%sql

USE dog_world;

CREATE TABLE people
    (
        name VARCHAR(100),
        birth_date DATE,
        birth_time TIME,
        birthdt DATETIME
    );

Empty DataFrame
Columns: []
Index: []

In [3]:
%%sql

INSERT INTO people (name, birth_date, birth_time, birthdt)
VALUES
    ('Matt', '2001-12-25', '11:00:00', '2001-12-25 11:00:00'),
    ('Lulu', '2003-01-20', '23:59:10', '2003-01-20 23:59:10'),
    ('Ben', '2010-10-02', '11:15:10', '2010-10-02 11:15:10'),
    ('Tom', '2009-10-22', '13:01:30', '2009-10-22 13:01:30'),
    ('Peter', '2001-11-28', '11:30:20', '2001-11-28 11:30:20')

Empty DataFrame
Columns: []
Index: []

In [4]:
%%sql

SELECT *
FROM people

    name  birth_date      birth_time             birthdt
0   Matt  2001-12-25 0 days 11:00:00 2001-12-25 11:00:00
1   Lulu  2003-01-20 0 days 23:59:10 2003-01-20 23:59:10
2    Ben  2010-10-02 0 days 11:15:10 2010-10-02 11:15:10
3    Tom  2009-10-22 0 days 13:01:30 2009-10-22 13:01:30
4  Peter  2001-11-28 0 days 11:30:20 2001-11-28 11:30:20