#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Formatting Dates - DATE_FORMAT()

In [2]:
%%sql

USE dog_world;

SELECT 
    name, 
    DATE_FORMAT(birth_date, '%a-%b-%e')
FROM people

    name DATE_FORMAT(birth_date, '%a-%b-%e')
0   Matt                          Tue-Dec-25
1   Lulu                          Mon-Jan-20
2    Ben                           Sat-Oct-2
3    Tom                          Thu-Oct-22
4  Peter                          Wed-Nov-28
5   Colt                           Thu-Aug-6

# Formatting TIME - DATE_FORMAT()

In [3]:
%%sql

USE dog_world;

SELECT 
    name, 
    DATE_FORMAT(birthdt, '%r')
FROM people

    name DATE_FORMAT(birthdt, '%r')
0   Matt                11:00:00 AM
1   Lulu                11:59:10 PM
2    Ben                11:15:10 AM
3    Tom                01:01:30 PM
4  Peter                11:30:20 AM
5   Colt                09:51:57 AM