#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Working with Foreign Key

In [2]:
%%sql

CREATE DATABASE blinkit

Empty DataFrame
Columns: []
Index: []

In [3]:
%%sql

USE blinkit;

CREATE TABLE customers
    (
        id INT AUTO_INCREMENT PRIMARY KEY,
        first_name VARCHAR(50),
        last_name VARCHAR(50),
        email VARCHAR(50)
    );

Empty DataFrame
Columns: []
Index: []

## FOREIGN KEY
#### Adding the FOREIGN KEY constraint makes sure that nobody can add a customer_id in the orders table that does not matches the id column of the customers table

In [6]:
%%sql

CREATE TABLE orders
    (
        id INT AUTO_INCREMENT PRIMARY KEY,
        order_date DATE,
        amount DECIMAL(8,2),
        customer_id INT,
        FOREIGN KEY (customer_id) REFERENCES customers(id)
    );

Empty DataFrame
Columns: []
Index: []

In [7]:
%%sql

INSERT INTO customers (first_name, last_name, email)
VALUES ('Boy', 'George', 'george@gmail.com'),
       ('George', 'Michael', 'gm@gmail.com'),
       ('David', 'Bowie', 'david@gmail.com'),
       ('Blue', 'Steele', 'blue@gmail.com'),
       ('Bette', 'Davis', 'bette@aol.com');


INSERT INTO orders (order_date, amount, customer_id)
VALUES ('2016-02-10', 99.99, 1),
       ('2017-11-11', 35.50, 1),
       ('2014-12-12', 800.67, 2),
       ('2015-01-03', 12.50, 2),
       ('1999-04-11', 450.25, 5);

Empty DataFrame
Columns: []
Index: []

In [8]:
%%sql

SELECT *
FROM customers

   id first_name last_name             email
0   1        Boy    George  george@gmail.com
1   2     George   Michael      gm@gmail.com
2   3      David     Bowie   david@gmail.com
3   4       Blue    Steele    blue@gmail.com
4   5      Bette     Davis     bette@aol.com

In [9]:
%%sql

SELECT *
FROM orders

   id  order_date  amount  customer_id
0   1  2016-02-10   99.99            1
1   2  2017-11-11   35.50            1
2   3  2014-12-12  800.67            2
3   4  2015-01-03   12.50            2
4   5  1999-04-11  450.25            5