#### Connection to MySQL

In [2]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

# LEFT JOIN
#### SQL LEFT JOIN (or LEFT OUTER JOIN) returns all records from the left table and the matching records from the right table. If there is no match for a row, the result will contain NULL values for all columns of the right table.

In [5]:
%%sql

USE blinkit;

SELECT *
FROM customers as c 
LEFT JOIN orders as o 
ON c.id = o.customer_id

,id,first_name,last_name,email,id,order_date,amount,customer_id
0,1,Boy,George,george@gmail.com,2.0,2017-11-11,35.50,1.0
1,1,Boy,George,george@gmail.com,1.0,2016-02-10,99.99,1.0
2,2,George,Michael,gm@gmail.com,4.0,2015-01-03,12.50,2.0
3,2,George,Michael,gm@gmail.com,3.0,2014-12-12,800.67,2.0
4,3,David,Bowie,david@gmail.com,NaN,None,None,NaN
5,4,Blue,Steele,blue@gmail.com,NaN,None,None,NaN
6,5,Bette,Davis,bette@aol.com,5.0,1999-04-11,450.25,5.0

## LEFT JOIN with GROUP BY

In [7]:
%%sql

SELECT
    CONCAT(c.first_name, ' ', c.last_name) as customer_name,
    CONCAT('$' ,SUM(o.amount)) as total_spent
FROM customers as c 
LEFT JOIN orders as o 
ON c.id = o.customer_id
GROUP BY customer_name
ORDER BY total_spent DESC

    customer_name total_spent
0  George Michael     $813.17
1     Bette Davis     $450.25
2      Boy George     $135.49
3     David Bowie        None
4     Blue Steele        None

#### Find the customers who didn't order anything

In [10]:
%%sql

SELECT
    CONCAT(c.first_name, ' ', c.last_name) as customer_name,
    CONCAT('$' ,SUM(o.amount)) as total_spent
FROM customers as c 
LEFT JOIN orders as o 
ON c.id = o.customer_id
GROUP BY customer_name
HAVING total_spent IS NULL
ORDER BY total_spent DESC

  customer_name total_spent
0   David Bowie        None
1   Blue Steele        None

### Using IFNULL
```sql
IFNULL(expression, 0)
```

In [15]:
%%sql

SELECT
    CONCAT(c.first_name, ' ', c.last_name) as customer_name,
    IFNULL(SUM(o.amount), 0) as total_spent
FROM customers as c 
LEFT JOIN orders as o 
ON c.id = o.customer_id
GROUP BY customer_name
ORDER BY total_spent DESC

    customer_name total_spent
0  George Michael      813.17
1     Bette Davis      450.25
2      Boy George      135.49
3     David Bowie        0.00
4     Blue Steele        0.00