#### MySQL Connection

In [2]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

# SQL MODES

In [3]:
%%sql

SELECT @@GLOBAL.sql_mode;

                                   @@GLOBAL.sql_mode
0  ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO...

In [4]:
%%sql

SELECT @@SESSION.sql_mode

                                  @@SESSION.sql_mode
0  ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO...

# SETTING MODES

In [ ]:

SET GLOBAL sql_mode = 'modes'
SET SESSION sql_mode = 'modes'

# STRICT TRANS TABLES (TRANSACTIONAL)

####  is a MySQL mode that forces the database to reject bad data instead of changing it quietly. If you try to save a wrong value, the server stops the command and shows an error.
## What It Does

- Stops bad inserts when text is too long or numbers are out of range.
- Rejects `NULL` values sent to columns that do not allow empty data.
- Stops rollbacks or cancels full transactions on transactional engines like InnoDB if a row fails.
- Prevents hidden data corruption from silent truncation.