#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Many to Many Relationship

In [2]:
%%sql

CREATE DATABASE tv_shows;

Empty DataFrame
Columns: []
Index: []

In [3]:
%%sql

USE tv_shows;

CREATE TABLE reviewers
    (
        id INT AUTO_INCREMENT PRIMARY KEY,
        first_name VARCHAR(50) NOT NULL,
        last_name VARCHAR(50) NOT NULL
    )

Empty DataFrame
Columns: []
Index: []

In [4]:
%%sql

CREATE TABLE series
    (
        id INT AUTO_INCREMENT PRIMARY KEY,
        title VARCHAR(100),
        released_year YEAR,
        genre VARCHAR(100)
    )

Empty DataFrame
Columns: []
Index: []

In [6]:
%%sql

CREATE TABLE reviews
    (
        id INT AUTO_INCREMENT PRIMARY KEY,
        rating DECIMAL(2,1),
        series_id INT,
        reviewer_id INT,
        FOREIGN KEY (series_id) REFERENCES series(id),
        FOREIGN KEY (reviewer_id) REFERENCES reviewers(id)
    )

Empty DataFrame
Columns: []
Index: []

In [7]:
%%sql

INSERT INTO series (title, released_year, genre) VALUES
    ('Archer', 2009, 'Animation'),
    ('Arrested Development', 2003, 'Comedy'),
    ("Bob's Burgers", 2011, 'Animation'),
    ('Bojack Horseman', 2014, 'Animation'),
    ("Breaking Bad", 2008, 'Drama'),
    ('Curb Your Enthusiasm', 2000, 'Comedy'),
    ("Fargo", 2014, 'Drama'),
    ('Freaks and Geeks', 1999, 'Comedy'),
    ('General Hospital', 1963, 'Drama'),
    ('Halt and Catch Fire', 2014, 'Drama'),
    ('Malcolm In The Middle', 2000, 'Comedy'),
    ('Pushing Daisies', 2007, 'Comedy'),
    ('Seinfeld', 1989, 'Comedy'),
    ('Stranger Things', 2016, 'Drama');

Empty DataFrame
Columns: []
Index: []

In [8]:
%%sql

INSERT INTO reviewers (first_name, last_name) VALUES
    ('Thomas', 'Stoneman'),
    ('Wyatt', 'Skaggs'),
    ('Kimbra', 'Masters'),
    ('Domingo', 'Cortes'),
    ('Colt', 'Steele'),
    ('Pinkie', 'Petit'),
    ('Marlon', 'Crafford');

Empty DataFrame
Columns: []
Index: []

In [9]:
%%sql

INSERT INTO reviews(series_id, reviewer_id, rating) VALUES
    (1,1,8.0),(1,2,7.5),(1,3,8.5),(1,4,7.7),(1,5,8.9),
    (2,1,8.1),(2,4,6.0),(2,3,8.0),(2,6,8.4),(2,5,9.9),
    (3,1,7.0),(3,6,7.5),(3,4,8.0),(3,3,7.1),(3,5,8.0),
    (4,1,7.5),(4,3,7.8),(4,4,8.3),(4,2,7.6),(4,5,8.5),
    (5,1,9.5),(5,3,9.0),(5,4,9.1),(5,2,9.3),(5,5,9.9),
    (6,2,6.5),(6,3,7.8),(6,4,8.8),(6,2,8.4),(6,5,9.1),
    (7,2,9.1),(7,5,9.7),
    (8,4,8.5),(8,2,7.8),(8,6,8.8),(8,5,9.3),
    (9,2,5.5),(9,3,6.8),(9,4,5.8),(9,6,4.3),(9,5,4.5),
    (10,5,9.9),
    (13,3,8.0),(13,4,7.2),
    (14,2,8.5),(14,3,8.9),(14,4,8.9);

Empty DataFrame
Columns: []
Index: []

In [15]:
%%sql

SELECT *
FROM reviewers
LIMIT 5;

   id first_name last_name
0   1     Thomas  Stoneman
1   2      Wyatt    Skaggs
2   3     Kimbra   Masters
3   4    Domingo    Cortes
4   5       Colt    Steele

In [14]:
%%sql

SELECT *
FROM series
LIMIT 5;

   id                 title  released_year      genre
0   1                Archer           2009  Animation
1   2  Arrested Development           2003     Comedy
2   3         Bob's Burgers           2011  Animation
3   4       Bojack Horseman           2014  Animation
4   5          Breaking Bad           2008      Drama

In [13]:
%%sql

SELECT *
FROM reviews
LIMIT 5;

   id rating  series_id  reviewer_id
0   1    8.0          1            1
1   2    7.5          1            2
2   3    8.5          1            3
3   4    7.7          1            4
4   5    8.9          1            5