In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

In [18]:
%%sql

USE instagram;

SELECT *
FROM likes

      user_id  photo_id          created_at
0           2         1 2026-08-10 18:45:50
1           2         4 2026-08-10 18:45:50
2           2         8 2026-08-10 18:45:50
3           2         9 2026-08-10 18:45:50
4           2        10 2026-08-10 18:45:50
...       ...       ...                 ...
8777      100       245 2026-08-10 18:45:50
8778      100       246 2026-08-10 18:45:50
8779      100       248 2026-08-10 18:45:50
8780      100       249 2026-08-10 18:45:50
8781      100       255 2026-08-10 18:45:50

[8782 rows x 3 columns]

In [11]:
%%sql

SELECT
    id,
    username,
    created_at
FROM users
ORDER BY created_at
LIMIT 5;

   id          username          created_at
0  80      Darby_Herzog 2016-05-06 00:14:21
1  67  Emilio_Bernier52 2016-05-06 13:04:30
2  63          Elenor88 2016-05-08 01:30:41
3  95          Nicole71 2016-05-09 17:30:22
4  38  Jordyn.Jacobson2 2016-05-14 07:56:26

In [14]:
%%sql

SELECT
    DAYNAME(created_at),
    COUNT(id)
FROM users
GROUP BY DAYNAME(created_at)
ORDER BY COUNT(id) DESC

  DAYNAME(created_at)  COUNT(id)
0            Thursday         16
1              Sunday         16
2              Friday         15
3             Tuesday         14
4              Monday         14
5           Wednesday         13
6            Saturday         12

In [17]:
%%sql

SELECT *
FROM users as u 
LEFT JOIN photos as p 
ON u.id = p.user_id
WHERE p.user_id IS NULL

,id,username,created_at,id,image_url,user_id,created_at
0,5,Aniya_Hackett,2016-12-07 01:04:39,None,None,None,None
1,7,Kasandra_Homenick,2016-12-12 06:50:08,None,None,None,None
2,14,Jaclyn81,2017-02-06 23:29:16,None,None,None,None
3,21,Rocio33,2017-01-23 11:51:15,None,None,None,None
4,24,Maxwell.Halvorson,2017-04-18 02:32:44,None,None,None,None
5,25,Tierra.Trantow,2016-10-03 12:49:21,None,None,None,None
6,34,Pearl7,2016-07-08 21:42:01,None,None,None,None
7,36,Ollie_Ledner37,2016-08-04 15:42:20,None,None,None,None
8,41,Mckenna17,2016-07-17 17:25:45,None,None,None,None
9,45,David.Osinski47,2017-02-05 21:23:37,None,None,None,None
10,49,Morgan.Kassulke,2016-10-30 12:42:31,None,None,None,None
11,53,Linnea59,2017-02-07 07:49:34,None,None,None,None
12,54,Duane60,2016-12-21 04:43:38,None,None,None,None
13,57,Julien_Schmidt,2017-02-02 23:12:48,None,None,None,None
14,66,Mike.Auer39,2016-07-01 17:36:15,None,None,None,None
15,68,Franco_Keebler64,2016-11-13 20:09:27,None,None,None,None
16,71,Nia_Haag,2016-05-14 15:38:50,None,None,None,None
17,74,Hulda.Macejkovic,2017-01-25 17:17:28,None,None,None,None
18,75,Leslie67,2016-09-21 05:14:01,None,None,None,None
19,76,Janelle.Nikolaus81,2016-07-21 09:26:09,None,None,None,None
20,80,Darby_Herzog,2016-05-06 00:14:21,None,None,None,None
21,81,Esther.Zulauf61,2017-01-14 17:02:34,None,None,None,None
22,83,Bartholome.Bernhard,2016-11-06 02:31:23,None,None,None,None
23,89,Jessyca_West,2016-09-14 23:47:05,None,None,None,None
24,90,Esmeralda.Mraz57,2017-03-03 11:52:27,None,None,None,None
25,91,Bethany20,2016-06-03 23:31:53,None,None,None,None

In [28]:
%%sql

SELECT 
    u.id,
    p.id as photo_id,
    u.username,
    p.image_url,
    COUNT(*)
FROM users as u 
JOIN photos as p 
ON u.id = p.user_id
JOIN likes as l 
ON p.id = l.photo_id
GROUP BY p.id
ORDER BY COUNT(*) DESC

     id  photo_id             username               image_url  COUNT(*)
0    52       145        Zack_Kemmer93     https://jarret.name        48
1    46       127      Malinda_Streich  https://celestine.name        43
2    65       182             Adelle96      https://dorcas.biz        43
3    44       123               Seth46      http://shannon.org        42
4    10        30      Presley_McClure        http://kenny.com        41
..   ..       ...                  ...                     ...       ...
252  51       139        Mariano_Koch3      https://seamus.org        27
253  88       238              Clint27        http://adela.com        27
254  72       195            Kathryn80   http://marcellus.info        26
255   1         1        Kenton_Kirlin       http://elijah.biz        25
256  86       223  Delfina_VonRueden68       http://howard.net        25

[257 rows x 5 columns]

In [30]:
%%sql

SELECT 
    SUM(p.id) / SUM(u.id) AS avg_post_times
FROM users as u 
JOIN photos as p 
ON u.id = p.user_id

  avg_post_times
0         2.7255

In [36]:
%%sql

SELECT
    t.tag_name,
    p.tag_id,
    COUNT(p.photo_id)
FROM photo_tags as p
JOIN tags as t 
ON p.tag_id = t.id
GROUP BY p.tag_id
ORDER BY COUNT(p.photo_id) DESC
LIMIT 5;

  tag_name  tag_id  COUNT(p.photo_id)
0    smile      21                 59
1    beach      20                 42
2    party      17                 39
3      fun      13                 38
4  concert      18                 24

In [48]:
%%sql

SELECT 
    u.username,
    l.user_id,
    COUNT(*) AS num_likes
FROM users as u 
JOIN likes as l 
ON u.id = l.user_id
GROUP BY l.user_id
HAVING num_likes = (
    SELECT
        COUNT(*)
    FROM photos
)

              username  user_id  num_likes
0        Aniya_Hackett        5        257
1            Bethany20       91        257
2              Duane60       54        257
3             Jaclyn81       14        257
4   Janelle.Nikolaus81       76        257
5       Julien_Schmidt       57        257
6             Leslie67       75        257
7    Maxwell.Halvorson       24        257
8            Mckenna17       41        257
9          Mike.Auer39       66        257
10            Nia_Haag       71        257
11      Ollie_Ledner37       36        257
12             Rocio33       21        257