#### Connection to MySQL server

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Show Databases

In [2]:
%%sql

SHOW DATABASES;

             Database
0  information_schema
1               mysql
2  performance_schema
3                 sys

# Create Databases

In [3]:
%%sql 

CREATE DATABASE bull_dog_world

Empty DataFrame
Columns: []
Index: []

In [6]:
%%sql

SHOW DATABASES;

             Database
0      bull_dog_world
1  information_schema
2               mysql
3  performance_schema
4                 sys

# Drop Databases

In [8]:
%%sql

DROP DATABASE bull_dog_world;

Empty DataFrame
Columns: []
Index: []

In [9]:
%%sql

SHOW DATABASES

             Database
0  information_schema
1               mysql
2  performance_schema
3                 sys