#### MySQL Connection

In [2]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

# DENSE_RANK & ROW_NUMBER()

# ROW_NUMBER()
#### ROW_NUMBER() window function assigns a unique, sequential integer to each row in a result set, starting at 1 for the first row.

In [10]:
%%sql
USE dog_world;

SELECT 
    emp_no,
    department,
    salary,
    ROW_NUMBER() OVER(PARTITION BY department ORDER BY salary DESC) as dept_row_number,
    RANK() OVER(ORDER BY salary DESC) AS overall_salary_rank
FROM employees
ORDER BY department

    emp_no        department  salary  dept_row_number  overall_salary_rank
0       17  customer service   61000                1                   11
1       20  customer service   56000                2                   16
2       21  customer service   55000                3                   17
3       16  customer service   45000                4                   18
4       18  customer service   40000                5                   19
5       15  customer service   38000                6                   20
6       19  customer service   31000                7                   21
7        4       engineering  103000                1                    2
8        7       engineering   91000                2                    3
9        6       engineering   89000                3                    4
10       1       engineering   80000                4                    5
11       3       engineering   70000                5                    7
12       2       engineering   69000                6                    9
13       5       engineering   67000                7                   10
14      10             sales  159000                1                    1
15      11             sales   72000                2                    6
16       9             sales   70000                3                    7
17      13             sales   61000                4                   11
18      14             sales   61000                5                   11
19      12             sales   60000                6                   14
20       8             sales   59000                7                   15

# DENSE RANK
#### DENSE_RANK() window function in MySQL assigns a sequential rank to each row within a partition, ensuring that tied values receive the same rank and no ranking numbers are skipped.

In [13]:
%%sql
USE dog_world;

SELECT 
    emp_no,
    department,
    salary,
    ROW_NUMBER() OVER(PARTITION BY department ORDER BY salary DESC) as dept_row_number,
    RANK() OVER(ORDER BY salary DESC) AS overall_salary_rank,
    DENSE_RANK() OVER(ORDER BY salary DESC) AS overall_dense_rank
FROM employees
ORDER BY overall_dense_rank

,emp_no,department,salary,dept_row_number,overall_salary_rank,overall_dense_rank
0,10,sales,159000,1,1,1
1,4,engineering,103000,1,2,2
2,7,engineering,91000,2,3,3
3,6,engineering,89000,3,4,4
4,1,engineering,80000,4,5,5
5,11,sales,72000,2,6,6
6,3,engineering,70000,5,7,7
7,9,sales,70000,3,7,7
8,2,engineering,69000,6,9,8
9,5,engineering,67000,7,10,9
10,17,customer service,61000,1,11,10
11,13,sales,61000,4,11,10
12,14,sales,61000,5,11,10
13,12,sales,60000,6,14,11
14,8,sales,59000,7,15,12
15,20,customer service,56000,2,16,13
16,21,customer service,55000,3,17,14
17,16,customer service,45000,4,18,15
18,18,customer service,40000,5,19,16
19,15,customer service,38000,6,20,17
20,19,customer service,31000,7,21,18