#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# DEFAULT Values
### We can assign a default value to a column in a table so that if nothing is entered then it shows that default value
```sql
CREATE TABLE table_name
    (
        column_1 VARCHAR(100) DEFAULT 'default_value',
        column_2 INT DEFAULT 51
    );
```

In [8]:
%%sql

USE dog_world;

CREATE TABLE dogs_3
    (
        name VARCHAR(100) DEFAULT 'john_doe',
        age INT DEFAULT 7
    );

Empty DataFrame
Columns: []
Index: []

In [10]:
%%sql

USE dog_world;

INSERT INTO dogs_3 (name, age)
VALUES
    ('jack', 9),
    ('mary', 2),
    (DEFAULT, 5),
    ('leslie', 6)

Empty DataFrame
Columns: []
Index: []

In [11]:
%%sql

SELECT *
FROM dogs_3

       name  age
0      jack    9
1      mary    2
2  john_doe    5
3    leslie    6

### NOT NULL and DEFAULT are not the same. You can set a value to NULL if you just have a DEFAULT value and NOT NULL is not enabled for that column

In [12]:
%%sql

INSERT INTO dogs_3 (name, age)
VALUES
    ('jack', 12),
    ('ginger', 10),
    ('salmon', 8),
    (NULL, NULL)

Empty DataFrame
Columns: []
Index: []

In [13]:
%%sql

SELECT *
FROM dogs_3

       name   age
0      jack   9.0
1      mary   2.0
2  john_doe   5.0
3    leslie   6.0
4      jack  12.0
5    ginger  10.0
6    salmon   8.0
7      None   NaN

In [14]:
%%sql

DROP TABLE dogs_3

Empty DataFrame
Columns: []
Index: []