In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Basics of Inserting Data
```sql
INSERT INTO table_name (column1, column2)
VALUES('Val1', val2)

In [10]:
%%sql

USE dog_world;

CREATE TABLE dogs(
    name VARCHAR(50),
    age INT
)

Empty DataFrame
Columns: []
Index: []

#### Inserting the data

In [13]:
%%sql

USE dog_world;

INSERT INTO dogs (name, age)
VALUES
    ('Ginger', 8), 
    ('Mogambo', 10),
    ('Young', 4)

Empty DataFrame
Columns: []
Index: []

#### Checking the data if it is inserted or not

In [15]:
%%sql

USE dog_world;

SELECT *
FROM dogs

      name  age
0   Ginger    8
1  Mogambo   10
2    Young    4

# Insert Data Exercise
#### Create a table called 'people'
#### 1.first_name - 20 char limit
#### 2.last_name - 20 char limit
#### 3.age
#### After creating these columns insert data in the table

In [16]:
%%sql

USE dog_world;

CREATE TABLE people(
    first_name VARCHAR(20),
    last_name VARCHAR(20),
    age INT
);

Empty DataFrame
Columns: []
Index: []

In [17]:
%%sql

USE dog_world;

INSERT INTO people (first_name, last_name, age)
VALUES
    ('Peter', 'Parker', 28),
    ('Tom', 'Holland', 32),
    ('Ben', 'Affleck', 72),
    ('Tony', 'Irons', 80)

Empty DataFrame
Columns: []
Index: []

In [19]:
%%sql

USE dog_world;

SELECT *
FROM people

  first_name last_name  age
0      Peter    Parker   28
1        Tom   Holland   32
2        Ben   Affleck   72
3       Tony     Irons   80

In [20]:
%%sql

USE dog_world;

DROP TABLE people

Empty DataFrame
Columns: []
Index: []