#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# NOT NULL
#### NULL and 0 are not the same since 0 is considered as a value but NULL means there is nothing there (empty).
#### Adding NOT NULL to column as a constraint makes sure the column will never have any NULL value

```sql
CREATE TABLE table_name
    (
        column_1 VARCHAR(100) NOT NULL
        column_2 INT NOT NULL
    );

```

In [2]:
%%sql

USE dog_world;

CREATE TABLE dogs_2
    (
        name VARCHAR(50) NOT NULL,
        age INT NOT NULL
    );

Empty DataFrame
Columns: []
Index: []

#### When we do a DESCRIBE on this new table we can clearly see that for NULL column it says NO

In [3]:
%%sql

USE dog_world;

DESCRIBE dogs_2

  Field         Type Null Key Default Extra
0  name  varchar(50)   NO        None
1   age          int   NO        None

In [4]:
%%sql

USE dog_world;

DROP TABLE dogs_2

Empty DataFrame
Columns: []
Index: []