#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# CHECK Constraint

In [2]:
%%sql

USE dog_world;

CREATE TABLE users
    (
        user_id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        age INT NOT NULL CHECK(age > 1)
    );

Empty DataFrame
Columns: []
Index: []

In [6]:
%%sql

INSERT INTO users (name, age)
VALUES 
    ('John', 19),
    ('Mary', 5),
    ('Tony', 9)

Empty DataFrame
Columns: []
Index: []

In [7]:
%%sql

SELECT *
FROM users

   user_id  name  age
0        4  John   19
1        5  Mary    5
2        6  Tony    9