#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Multiple Column Constraints

In [11]:
%%sql

USE dog_world;

CREATE TABLE new_users
    (
        name VARCHAR(100) NOT NULL,
        user_type VARCHAR(20) NOT NULL,
        age INT NOT NULL,
        CONSTRAINT name_userType UNIQUE(name, user_type)
    );

Empty DataFrame
Columns: []
Index: []

In [13]:
%%sql

INSERT INTO new_users
VALUES
    ('Tom', 'player', 20),
    ('Jaine', 'player', 22),
    ('May', 'employee', 25),
    ('Mary', 'teacher', 22)

Empty DataFrame
Columns: []
Index: []

In [14]:
%%sql

SELECT *
FROM new_users

    name user_type  age
0  Jaine    player   22
1   Mary   teacher   22
2    May  employee   25
3    Tom    player   20

In [15]:
%%sql

CREATE TABLE houses
    (
        sale_price INT NOT NULL,
        purchase_price INT NOT NULL,
        CONSTRAINT sale_gt_purchase CHECK(sale_price > purchase_price)
    )

Empty DataFrame
Columns: []
Index: []

In [17]:
%%sql

INSERT INTO houses
VALUES
    (1000, 800),
    (1500, 1000),
    (1200, 800),
    (1500, 1200)

Empty DataFrame
Columns: []
Index: []