#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Named Constraints

In [3]:
%%sql

USE dog_world;

CREATE TABLE site_users
    (
        user_id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        age INT NOT NULL,
        CONSTRAINT age_check CHECK(age >= 18)        
    )

Empty DataFrame
Columns: []
Index: []

In [6]:
%%sql

INSERT INTO site_users (name, age)
VALUES 
    ('John', 19),
    ('Harry', 21),
    ('Tom', 18),
    ('Ben', 20),
    ('Mary', 19)

Empty DataFrame
Columns: []
Index: []

In [7]:
%%sql

SELECT *
FROM site_users

   user_id   name  age
0        6   John   19
1        7  Harry   21
2        8    Tom   18
3        9    Ben   20
4       10   Mary   19