#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# UNIQUE Constraint

In [6]:
%%sql

USE dog_world;

CREATE TABLE workers
    (
        worker_id INT AUTO_INCREMENT,
        name VARCHAR(50) NOT NULL,
        phone CHAR(10) NOT NULL UNIQUE,
        PRIMARY KEY(worker_id)
    );

Empty DataFrame
Columns: []
Index: []

In [7]:
%%sql

INSERT INTO workers (name, phone)
VALUES
    ('John', 9415336556),
    ('Maine', 9335447688),
    ('Layz', 9867665667)

Empty DataFrame
Columns: []
Index: []

In [8]:
%%sql

SELECT *
FROM workers

   worker_id   name       phone
0          1   John  9415336556
1          2  Maine  9335447688
2          3   Layz  9867665667