#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# CHAR_LENGTH - String Function
### CHAR_LENGTH() counts characters, while LENGTH() counts bytes
```sql
SELECT 
    CHAR_LENGTH(column_name)
FROM table_name
```

In [2]:
%%sql

USE book_shop;

SELECT *
FROM books
LIMIT 5;

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,1,The Namesake,Jhumpa,Lahiri,2003,32,291
1,2,Norse Mythology,Neil,Gaiman,2016,43,304
2,3,American Gods,Neil,Gaiman,2001,12,465
3,4,Interpreter of Maladies,Jhumpa,Lahiri,1996,97,198
4,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352

In [5]:
%%sql

SELECT
    CHAR_LENGTH(title) AS title_length,
    author_fname,
    author_lname
FROM books
LIMIT 5;

   title_length author_fname author_lname
0            12       Jhumpa       Lahiri
1            15         Neil       Gaiman
2            13         Neil       Gaiman
3            23       Jhumpa       Lahiri
4            32         Dave       Eggers