#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# REVERSE - String Function
#### It will take in whatever string we provide it and it will REVERESE it
```sql
SELECT 
    REVERSE(column_name)
FROM table_name
```

In [3]:
%%sql

USE book_shop;

SELECT 
    REVERSE(title)
FROM books
LIMIT 10;

                              REVERSE(title)
0                               ekasemaN ehT
1                            ygolohtyM esroN
2                              sdoG naciremA
3                    seidalaM fo reterpretnI
4           levoN A :gniK eht rof margoloH A
5                                 elcriC ehT
6  yalC & reilavaK fo serutnevdA gnizamA ehT
7                                  sdiK tsuJ
8  suineG gnireggatS fo kroW gnikaerbtraeH A
9                                   enilaroC

In [6]:
%%sql

SELECT 
    CONCAT(
        author_fname, 
        REVERSE(author_fname)
        ) AS weird_string
FROM books
LIMIT 10;

     weird_string
0    JhumpaapmuhJ
1        NeillieN
2        NeillieN
3    JhumpaapmuhJ
4        DaveevaD
5        DaveevaD
6  MichaelleahciM
7      PattiittaP
8        DaveevaD
9        NeillieN