#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# SUBSTRING / SUBSTR - String Function
```sql
SELECT
    SUBSTRING(column_1, start_point, end_point)
FROM table_name
```

In [5]:
%%sql

USE book_shop;

SELECT 
    SUBSTRING(title, 1, 15) AS partial_name
FROM books
LIMIT 5;

      partial_name
0     The Namesake
1  Norse Mythology
2    American Gods
3  Interpreter of
4  A Hologram for

### We will try to get the first character of author's last name

In [7]:
%%sql

SELECT
    SUBSTRING(author_lname, 1, 1) AS author_initials
FROM books
LIMIT 5;

  author_initials
0               L
1               G
2               G
3               L
4               E