#### Connection to MySQL

In [2]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

# UPPER() & LOWER() case
#### UPPER
```sql
SELECT 
    UPPER(column_name)
FROM table_name
```
#### LOWER
```sql
SELECT 
    LOWER(column_name)
FROM table_name
```

In [4]:
%%sql

USE book_shop;

SELECT *
FROM books
LIMIT 5;

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,1,The Namesake,Jhumpa,Lahiri,2003,32,291
1,2,Norse Mythology,Neil,Gaiman,2016,43,304
2,3,American Gods,Neil,Gaiman,2001,12,465
3,4,Interpreter of Maladies,Jhumpa,Lahiri,1996,97,198
4,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352

In [6]:
%%sql

SELECT
    UPPER(author_fname) AS AUTHOR_FIRST_NAME,
    LOWER(author_lname) AS AUTHOR_LAST_NAME
FROM books
LIMIT 5;

  AUTHOR_FIRST_NAME AUTHOR_LAST_NAME
0            JHUMPA           lahiri
1              NEIL           gaiman
2              NEIL           gaiman
3            JHUMPA           lahiri
4              DAVE           eggers

In [8]:
%%sql

SELECT 
    CONCAT(
        'I LOVE',
        ' ',
        UPPER(title)
        )
FROM books
LIMIT 5;

  CONCAT(\n        'I LOVE',\n        ' ',\n        UPPER(title)\n        )
0                                I LOVE THE NAMESAKE
1                             I LOVE NORSE MYTHOLOGY
2                               I LOVE AMERICAN GODS
3                     I LOVE INTERPRETER OF MALADIES
4            I LOVE A HOLOGRAM FOR THE KING: A NOVEL