#### MySQL Connection

In [2]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# AVG

#### Find the average number of pages for all the books combined in the database

In [3]:
%%sql

USE book_shop;

SELECT 
    AVG(pages)
FROM books

  AVG(pages)
0   348.5789

#### AVG all the pages each author has written

In [6]:
%%sql

SELECT
    CONCAT(author_fname, ' ', author_lname) AS author_name,
    AVG(pages) AS average_pages
FROM books
GROUP BY author_name
ORDER BY average_pages DESC

             author_name average_pages
0         Michael Chabon      634.0000
1            Dave Eggers      431.0000
2          Freida Harris      428.0000
3        George Saunders      367.0000
4         Raymond Carver      351.0000
5   David Foster Wallace      336.0000
6            Neil Gaiman      325.6667
7            Don DeLillo      320.0000
8            Patti Smith      304.0000
9             Dan Harris      256.0000
10         Jhumpa Lahiri      244.5000
11        John Steinbeck      181.0000

#### Calculate the average stock quantity for books released in the same year

In [11]:
%%sql

SELECT 
    released_year,
    AVG(stock_quantity) AS avg_stock_quantity,
    COUNT(*) AS '# of books'
FROM books
GROUP BY released_year

    released_year avg_stock_quantity  # of books
0            2003            66.0000           2
1            2016            43.0000           1
2            2001           134.3333           3
3            1996            97.0000           1
4            2012           154.0000           1
5            2013            26.0000           1
6            2000            68.0000           1
7            2010            55.0000           1
8            1981            23.0000           1
9            1989            12.0000           1
10           1985            49.0000           1
11           1945            95.0000           1
12           2004           172.0000           1
13           2005            92.0000           1
14           2014            29.0000           1
15           2017          1000.0000           1