#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# GROUP BY
##### GROUP BY summarizes or aggregates identical data into single rows.
```sql
SELECT 
    column1,
    column2,
    column3
FROM table_name
WHERE condition
GROUP BY column2
ORDER BY column1
```

In [12]:
%%sql

USE book_shop;

SELECT author_lname
FROM books
GROUP BY author_lname

      author_lname
0           Lahiri
1           Gaiman
2           Eggers
3           Chabon
4            Smith
5           Carver
6          DeLillo
7        Steinbeck
8   Foster Wallace
9           Harris
10        Saunders

In [30]:
%%sql

SELECT 
    CONCAT(author_fname, ' ', author_lname) AS author_name,
    COUNT(*) AS books_written,
    SUM(stock_quantity) AS total_stock,
    ROUND(AVG(stock_quantity),2) AS avg_stock
FROM books
GROUP BY author_name
ORDER BY books_written DESC

             author_name  books_written total_stock avg_stock
0            Neil Gaiman              3         155     51.67
1            Dave Eggers              3         284     94.67
2          Jhumpa Lahiri              2         129     64.50
3         Raymond Carver              2          35     17.50
4   David Foster Wallace              2         264    132.00
5         Michael Chabon              1          68     68.00
6            Patti Smith              1          55     55.00
7            Don DeLillo              1          49     49.00
8         John Steinbeck              1          95     95.00
9             Dan Harris              1          29     29.00
10         Freida Harris              1         287    287.00
11       George Saunders              1        1000   1000.00

In [32]:
%%sql

SELECT 
    released_year,
    COUNT(*) AS books_written
FROM books
GROUP BY released_year
ORDER BY books_written DESC

    released_year  books_written
0            2001              3
1            2003              2
2            2016              1
3            1996              1
4            2012              1
5            2013              1
6            2000              1
7            2010              1
8            1981              1
9            1989              1
10           1985              1
11           1945              1
12           2004              1
13           2005              1
14           2014              1
15           2017              1