#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# MIN & MAX

In [9]:
%%sql

USE book_shop;

SELECT 
    MIN(released_year) AS Min_Year
FROM books

   Min_Year
0      1945

In [10]:
%%sql

USE book_shop;

SELECT 
    MAX(released_year) AS Max_Year
FROM books

   Max_Year
0      2017

In [5]:
%%sql

SELECT 
    MIN(author_lname)
FROM books

  MIN(author_lname)
0            Carver

In [6]:
%%sql

SELECT 
    MAX(author_lname)
FROM books

  MAX(author_lname)
0         Steinbeck

#### I want to know the title of the longest book

In [16]:
%%sql

SELECT
    title,
    MAX(pages) AS Max_Pages
FROM books
GROUP BY title
ORDER BY Max_Pages DESC
LIMIT 1;

                                       title  Max_Pages
0  The Amazing Adventures of Kavalier & Clay        634