#### MySQL Connection

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# SUM

#### Find the total number of pages for all the books combined in the database

In [2]:
%%sql

USE book_shop;

SELECT 
    SUM(pages)
FROM books

  SUM(pages)
0       6623

#### Sum all the pages each author has written

In [4]:
%%sql

SELECT
    CONCAT(author_fname, ' ', author_lname) AS author_name,
    SUM(pages) AS total_pages
FROM books
GROUP BY author_name
ORDER BY total_pages DESC

             author_name total_pages
0            Dave Eggers        1293
1            Neil Gaiman         977
2         Raymond Carver         702
3   David Foster Wallace         672
4         Michael Chabon         634
5          Jhumpa Lahiri         489
6          Freida Harris         428
7        George Saunders         367
8            Don DeLillo         320
9            Patti Smith         304
10            Dan Harris         256
11        John Steinbeck         181