#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# DISTINCT
```sql
SELECT 
    DISTINCT column_name
FROM books
```

In [9]:
%%sql

USE book_shop;

SELECT
    DISTINCT author_lname
FROM books

      author_lname
0           Lahiri
1           Gaiman
2           Eggers
3           Chabon
4            Smith
5           Carver
6          DeLillo
7        Steinbeck
8   Foster Wallace
9           Harris
10        Saunders

In [11]:
%%sql

SELECT
    DISTINCT released_year
FROM books

    released_year
0            2003
1            2016
2            2001
3            1996
4            2012
5            2013
6            2000
7            2010
8            1981
9            1989
10           1985
11           1945
12           2004
13           2005
14           2014
15           2017

In [15]:
%%sql

SELECT 
    DISTINCT CONCAT(author_fname, ' ', author_lname) AS author_full_name
FROM books

        author_full_name
0          Jhumpa Lahiri
1            Neil Gaiman
2            Dave Eggers
3         Michael Chabon
4            Patti Smith
5         Raymond Carver
6            Don DeLillo
7         John Steinbeck
8   David Foster Wallace
9             Dan Harris
10         Freida Harris
11       George Saunders

In [16]:
%%sql

SELECT
    DISTINCT author_fname,
    author_lname
FROM books

   author_fname    author_lname
0        Jhumpa          Lahiri
1          Neil          Gaiman
2          Dave          Eggers
3       Michael          Chabon
4         Patti           Smith
5       Raymond          Carver
6           Don         DeLillo
7          John       Steinbeck
8         David  Foster Wallace
9           Dan          Harris
10       Freida          Harris
11       George        Saunders