#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# LIMIT

In [5]:
%%sql

USE book_shop;

SELECT *
FROM books
LIMIT 5;

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,1,The Namesake,Jhumpa,Lahiri,2003,32,291
1,2,Norse Mythology,Neil,Gaiman,2016,43,304
2,3,American Gods,Neil,Gaiman,2001,12,465
3,4,Interpreter of Maladies,Jhumpa,Lahiri,1996,97,198
4,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352

# LIMIT (Selective Range)

```sql
SELECT *
FROM table_name
LIMIT 4, 10
```
#### So here 4 is the point where we want to extract from and 10 defines the number of rows we want
#### Basically 4 is the Starting row and 10 says how many rows to extract

In [10]:
%%sql

SELECT *
FROM books
LIMIT 3,5;

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,4,Interpreter of Maladies,Jhumpa,Lahiri,1996,97,198
1,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352
2,6,The Circle,Dave,Eggers,2013,26,504
3,7,The Amazing Adventures of Kavalier & Clay,Michael,Chabon,2000,68,634
4,8,Just Kids,Patti,Smith,2010,55,304