#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# CASE Statements

In [8]:
%%sql

USE book_shop;

SELECT
    title, 
    released_year,
    CASE
        WHEN released_year BETWEEN 2001 AND 2012 THEN 'Modern Literature'
        WHEN released_year > 2012 THEN 'Genz Literature'
        ELSE '20th Cent Lit'
    END AS Genre
FROM books

,title,released_year,Genre
0,The Namesake,2003,Modern Literature
1,Norse Mythology,2016,Genz Literature
2,American Gods,2001,Modern Literature
3,Interpreter of Maladies,1996,20th Cent Lit
4,A Hologram for the King: A Novel,2012,Modern Literature
5,The Circle,2013,Genz Literature
6,The Amazing Adventures of Kavalier & Clay,2000,20th Cent Lit
7,Just Kids,2010,Modern Literature
8,A Heartbreaking Work of Staggering Genius,2001,Modern Literature
9,Coraline,2003,Modern Literature
10,What We Talk About When We Talk About Love: St...,1981,20th Cent Lit
11,Where I'm Calling From: Selected Stories,1989,20th Cent Lit
12,White Noise,1985,20th Cent Lit
13,Cannery Row,1945,20th Cent Lit
14,Oblivion: Stories,2004,Modern Literature
15,Consider the Lobster,2005,Modern Literature
16,10% Happier,2014,Genz Literature
17,fake_book,2001,Modern Literature
18,Lincoln In The Bardo,2017,Genz Literature

In [11]:
%%sql

SELECT
    title,
    stock_quantity,
    CASE
        WHEN stock_quantity BETWEEN 0 AND 10 THEN '*'
        WHEN stock_quantity BETWEEN 11 AND 20 THEN '**'
        WHEN stock_quantity BETWEEN 21 AND 30 THEN '***'
        ELSE '****'
    END AS stock_rating
FROM books

,title,stock_quantity,stock_rating
0,The Namesake,32,****
1,Norse Mythology,43,****
2,American Gods,12,**
3,Interpreter of Maladies,97,****
4,A Hologram for the King: A Novel,154,****
5,The Circle,26,***
6,The Amazing Adventures of Kavalier & Clay,68,****
7,Just Kids,55,****
8,A Heartbreaking Work of Staggering Genius,104,****
9,Coraline,100,****
10,What We Talk About When We Talk About Love: St...,23,***
11,Where I'm Calling From: Selected Stories,12,**
12,White Noise,49,****
13,Cannery Row,95,****
14,Oblivion: Stories,172,****
15,Consider the Lobster,92,****
16,10% Happier,29,***
17,fake_book,287,****
18,Lincoln In The Bardo,1000,****