#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# IS NULL

In [3]:
%%sql

USE book_shop;

SELECT *
FROM books
LIMIT 2;

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,1,The Namesake,Jhumpa,Lahiri,2003,32,291
1,2,Norse Mythology,Neil,Gaiman,2016,43,304

In [4]:
%%sql

INSERT INTO books (title, author_fname, author_lname)
VALUES('A good day to live!', 'Fischer', 'Raymond')

Empty DataFrame
Columns: []
Index: []

### Using IS NULL we are able to locate the released_year with NULL value

In [6]:
%%sql

SELECT *
FROM books
WHERE released_year IS NULL

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,20,A good day to live!,Fischer,Raymond,None,None,None

# IS NOT NULL

In [7]:
%%sql

SELECT *
FROM books
WHERE released_year IS NOT NULL

,book_id,title,author_fname,author_lname,released_year,stock_quantity,pages
0,1,The Namesake,Jhumpa,Lahiri,2003,32,291
1,2,Norse Mythology,Neil,Gaiman,2016,43,304
2,3,American Gods,Neil,Gaiman,2001,12,465
3,4,Interpreter of Maladies,Jhumpa,Lahiri,1996,97,198
4,5,A Hologram for the King: A Novel,Dave,Eggers,2012,154,352
5,6,The Circle,Dave,Eggers,2013,26,504
6,7,The Amazing Adventures of Kavalier & Clay,Michael,Chabon,2000,68,634
7,8,Just Kids,Patti,Smith,2010,55,304
8,9,A Heartbreaking Work of Staggering Genius,Dave,Eggers,2001,104,437
9,10,Coraline,Neil,Gaiman,2003,100,208
10,11,What We Talk About When We Talk About Love: St...,Raymond,Carver,1981,23,176
11,12,Where I'm Calling From: Selected Stories,Raymond,Carver,1989,12,526
12,13,White Noise,Don,DeLillo,1985,49,320
13,14,Cannery Row,John,Steinbeck,1945,95,181
14,15,Oblivion: Stories,David,Foster Wallace,2004,172,329
15,16,Consider the Lobster,David,Foster Wallace,2005,92,343
16,17,10% Happier,Dan,Harris,2014,29,256
17,18,fake_book,Freida,Harris,2001,287,428
18,19,Lincoln In The Bardo,George,Saunders,2017,1000,367

In [8]:
%%sql

DELETE FROM books
WHERE released_year IS NULL

Empty DataFrame
Columns: []
Index: []