#### Connection with MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Auto-Increment
```sql
CREATE TABLE table_name
    (
        id_column INT AUTO_INCREMENT,
        column_1 VARCHAR(100), 
        column_2 INT,
        PRIMARY KEY(id_column)
    )
```

In [2]:
%%sql

USE dog_world;

CREATE TABLE dogs_5
    (
        dog_id INT AUTO_INCREMENT,
        name VARCHAR(100) NOT NULL,
        age INT NOT NULL,
        PRIMARY KEY(dog_id)
    )

Empty DataFrame
Columns: []
Index: []

In [3]:
%%sql

INSERT INTO dogs_5 (name, age)
VALUES
    ('ginger', 2),
    ('scatt', 7),
    ('bratt', 4),
    ('flat', 1),
    ('matt', 2);

Empty DataFrame
Columns: []
Index: []

#### We can see that the dog_id got filled through AUTO_INCREMENT

In [5]:
%%sql

SELECT *
FROM dogs_5

   dog_id    name  age
0       1  ginger    2
1       2   scatt    7
2       3   bratt    4
3       4    flat    1
4       5    matt    2

In [6]:
%%sql

DROP TABLE dogs_5

Empty DataFrame
Columns: []
Index: []