#### Connection to MySQL

In [1]:
%load_ext sql
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False

import os
from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL

load_dotenv()

url = URL.create("mysql+pymysql",
                 username="root",
                 password=os.getenv('MYSQL_PW'),
                 host="localhost")
engine = create_engine(url)
%sql engine

# Primary Keys : Unique Identifier
```sql
CREATE TABLE table_name
    (
        id_column INT NOT NULL PRIMARY KEY,
        column_1 VARCHAR(100),
        column_2 INT
    )
```
### Another way
```sql
CREATE TABLE table_name
    (
        id_column INT NOT NULL,
        name VARCHAR(100),
        age INT,
        PRIMARY KEY(id_column)
    );
```

### Specifying NOT NULL for a primary key column is redundant since a primary key column can never be NULL

In [8]:
%%sql

USE dog_world;

CREATE TABLE dogs_4
    (
        dog_id INT NOT NULL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        age INT NOT NULL
    )

Empty DataFrame
Columns: []
Index: []

In [9]:
%%sql

INSERT INTO dogs_4 (dog_id, name, age)
VALUES
    (1, 'tom', 5),
    (2, 'yanky', 7),
    (3, 'slue', 2),
    (4, 'green', 3),
    (5, 'gray', 2);

Empty DataFrame
Columns: []
Index: []

### When we do a DESCRIBE on this table we can see that the KEY column shows dog_id as PRIMARY KEY

In [10]:
%%sql

DESCRIBE dogs_4

    Field          Type Null  Key Default Extra
0  dog_id           int   NO  PRI    None
1    name  varchar(100)   NO         None
2     age           int   NO         None

In [11]:
%%sql
SELECT *
FROM dogs_4

   dog_id   name  age
0       1    tom    5
1       2  yanky    7
2       3   slue    2
3       4  green    3
4       5   gray    2

In [12]:
%%sql

DROP TABLE dogs_4

Empty DataFrame
Columns: []
Index: []